language: java

script: ./gradlew check javadoc

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
        branch: master
    local-dir: build/docs/javadoc

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: build/libs/yggdrasil.jar
    on:
      repo: FRC3161/Yggdrasil
      tags: true
    skip_cleanup: true
    overwrite: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
